
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-app-siji-io-v1-helmchart
  failurePolicy: Fail
  name: vhelmchart.kb.io
  rules:
  - apiGroups:
    - app.siji.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - helmcharts
  sideEffects: None
