# permissions for end users to view helmdogs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helmdog-viewer-role
rules:
- apiGroups:
  - app.siji.io
  resources:
  - helmdogs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.siji.io
  resources:
  - helmdogs/status
  verbs:
  - get
