# permissions for end users to edit helmcharts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helmchart-editor-role
rules:
- apiGroups:
  - app.k8s.io
  resources:
  - helmcharts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.k8s.io
  resources:
  - helmcharts/status
  verbs:
  - get
