apiVersion: app.siji.io/v1
kind: HelmRelease
metadata:
  name: nginx
spec:
  chart:
    address: https://gitlab.com/chenzhiwei/charts/-/raw/master/release/nginx-0.1.0.tgz
  values:
    replicaCount: 1
    image:
      repository: docker.io/library/nginx
      tag: alpine
