apiVersion: app.siji.io/v1
kind: HelmDog
metadata:
  name: helmdog-sample
  finalizers:
  - abc/finalizer
spec:
  resources:
  - group: ""
    version: v1
    kind: Service
    name: nginx
    namespace: default
  - group: apps
    version: v1
    kind: Deployment
    name: nginx
    namespace: default
