name: PUSH - build docker image
on:
  push:
    branches:
    - master
    tags:
    - "*"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - name: checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: setup golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: login docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: build docker image
      run: make docker-build

    - name: publish docker image
      run: make docker-push
